#!/usr/bin/env python3
"""
mailroom.py -
    1) prompt user for 3 actions - Send thank you, create report or quit
Author: JohnR
Version: .3
Date: 12/25/2018
Notes: Completed structure for main loop. Completed get_input function.
"""


def main():
    """
    Create a list of donor and amounts, then get user input for the
    various actions available.
    :return:
    """
    donors = [                 # TODO: May need to add dates here
        'Oprah', [5, 10, 20],
        'Sting', [2043.23, 23456.23, 1665.224],
        'Bono', [25.20, 954.34, 340.234],
    ]

    while True:
        choice = get_input()

        if choice == 1:
            print('Exiting program.')
            break
        elif choice == 2:
            print('here we send a thank you')
        elif choice == 3:
            print('we would print a report here')


def get_input():
    """
    Get user input
    :return: User choice from menu
    """
    print('Please choose from the following menu: ')
    print('1 Quit')
    print('2 Send a thank you')
    print('3 Create a report')

    while True:
        cmd = input('Please pick a number between 1 and 3: ')
        cmd = int(cmd)
        if cmd not in range(1, 4):
            break
        else:
            return cmd


def thank_you():
    """
    send a thank you
    :return: thank you
    """
    # TODO: Prompt for full name
    # TODO: If name not in list, add to list and use it
    # TODO: If 'list' show donor list and re-prompt
    # TODO: If name in list, use it
    # TODO: Once name is selected prompt for donation amount
    # TODO: Turn amount into number
    # TODO: Add amount to the donation history for that user
    # TODO: Use string formatting to compose an email thanking the donor
    # TODO: Print thank you to screen and return to original promport
    pass


def create_report():
    """
    create a report
    :return: report
    """
    # TODO: Print a list of donors sorted by historical donation amount
    # TODO:     List donor name, number of donation and average donation
    # TODO:     amount (summary of each only)
    # TODO: Return to original prompt
    # TODO: User should be able to quit current task and return to prompt
    pass


if __name__ == '__main__':
    main()
