def gridPrinter():
    print('+' + ' -' * 4 + ' +' + ' -' * 4 + ' +')
    print()
    print('|' + ' ' * 9 + '|' + ' ' * 9 + '|')
    print()
    print('|' + ' ' * 9 + '|' + ' ' * 9 + '|')
    print()
    print('|' + ' ' * 9 + '|' + ' ' * 9 + '|')
    print()
    print('|' + ' ' * 9 + '|' + ' ' * 9 + '|')
    print()
    print('+' + ' -' * 4 + ' +' + ' -' * 4 + ' +')
    print()
    print('|' + ' ' * 9 + '|' + ' ' * 9 + '|')
    print()
    print('|' + ' ' * 9 + '|' + ' ' * 9 + '|')
    print()
    print('|' + ' ' * 9 + '|' + ' ' * 9 + '|')
    print()
    print('|' + ' ' * 9 + '|' + ' ' * 9 + '|')
    print()
    print('+' + ' -' * 4 + ' +' + ' -' * 4 + ' +')
gridPrinter()
     