# grid_part1.py
# output is a basic two by two grid for part 1 exercise of Lesson02
# By LouReis
def grid():
  print(2*(plus + 5*(space + minus) + space) + plus)
  print()
  print(2*(bar + 11*space) + bar)
  print()
  print(2*(bar + 11*space) + bar)
  print()
  print(2*(bar + 11*space) + bar)
  print()
  print(2*(bar + 11*space) + bar)
  print()
  print(2*(plus + 5*(space + minus) + space) + plus)
  print()
  print(2*(bar + 11*space) + bar)
  print()
  print(2*(bar + 11*space) + bar)
  print()
  print(2*(bar + 11*space) + bar)
  print()
  print(2*(bar + 11*space) + bar)
  print()
  print(2*(plus + 5*(space + minus) + space) + plus)
